site_name: OMATH Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  font:
    text: Roboto Condensed
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
extra_css:
  - styles/fonts.css
  - styles/center.css