site_name: OMATH Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  font:
    text: Roboto Condensed
extra_css:
  - styles/fonts.css
  - styles/center.css